import Footer from '@/components/layout/footer'
import Header from '@/components/layout/header/header'
import { gilroy } from '@/lib/utils/font'
import type { Metadata } from "next"

import { i18n, Locale } from '@/i18n-config'
import "../globals.css"

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'),
  title: "Artichoke",
  description: "Generated by create next app",
  openGraph: {
    title: 'Artichoke',
    description: 'Generated by create next app',
    images: [
      {
        url: '/Logo.svg',
        width: 1200,
        height: 630,
        alt: 'Artichoke',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Artichoke',
    description: 'Generated by create next app',
    images: ['/Logo.svg'],
  },
}

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { lang: string } | Promise<{ lang: string }>
}) {
  const resolved = await params
  const lang = resolved.lang as Locale

  return (
    <html lang={lang}>
      <body
        className={`${gilroy.variable} antialiased`}
      >
          <Header />
          {children}
          <Footer />
      </body>
    </html>
  )
}
