import Footer from '@/components/layout/footer'
import Header from '@/components/layout/header/header'
import { gilroy } from '@/lib/utils/font'
import type { Metadata } from "next"

import { i18n, Locale } from '@/i18n-config'
import { Suspense } from 'react'
import "../globals.css"


export const metadata: Metadata = {
  title: "Artichoke",
  description: "Generated by create next app",
}

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { lang: string } | Promise<{ lang: string }>
}) {
  const resolved = await params
  const lang = resolved.lang as Locale

  return (
    <html lang={lang}>
      <body
        className={`${gilroy.variable} antialiased`}
      >
        <Suspense>
          <Header />
          {children}
          <Footer />
        </Suspense>
      </body>
    </html>
  )
}
