import Footer from '@/components/layout/footer'
import Header from '@/components/layout/header/header'
import { gilroy } from '@/lib/utils/font'
import type { Metadata } from "next"

import { i18n, Locale } from '@/i18n-config'
import { getDictionary } from '@/lib/utils/get-dictionary'
import "../globals.css"

export const metadata: Metadata = {
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || 'https://artichoke.com'),
  title: {
    default: 'Artichoke Studio',
    template: "%s | Artichoke"
  },
  description: "Artichoke Interiors is an interior design studio creating personalized residential and commercial spaces focused on harmony, functionality, and emotional comfort.",
  openGraph: {
    type: 'website',
    title: 'Artichoke',
    locale: 'en_US',
    description: 'Artichoke Interiors is an interior design studio creating personalized residential and commercial spaces focused on harmony, functionality, and emotional comfort.',
    images: [
      {
        url: '/Logo.svg',
        width: 1200,
        height: 630,
        alt: 'Artichoke',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Artichoke',
    description: 'Generated by create next app',
    images: ['/Logo.svg'],
  },
  keywords: [
    'IR INTERIORS STUDIO',
    'IR INTERIORS ',
    'IR STUDIO',
    'Ivan Railean',
    'IVAN RAILEAN',
    'Artichoke',
    'Artichoke Studio',
    'Artichoke Interiors',
    'interior design',
    'interior design studio',
    'interior design firm',
    'interior design company',
    'interior design agency',
    'interior design services',
    'modern interior design',
    'custom interior design',
    'residential interior design',
    'commercial interior design'
  ],
  robots: {
    index: true,
    follow: true
  }
}

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: { lang: string } | Promise<{ lang: string }>
}) {
  const resolved = await params
  const lang = resolved.lang as Locale
  const dictionary = await getDictionary(lang)

  return (
    <html lang={lang}>
      <body
        className={`${gilroy.variable} antialiased`}
      >
          <Header dictionary={dictionary} />
          {children}
          <Footer />
      </body>
    </html>
  )
}
